### PR TITLE
Updated README and fixed highlighting issues

### PR DESCRIPTION
**Pull request by colin-axner**
Added Fee1, Fee2 to README. Added spaces to fix non-highlighting issues.

### CODE REVIEW

**Comment by AdityaSripal** [comment]
What's the issue with forcing first input to pay fee again?

**Comment by colin-axner** [comment]
No issue, @hamdiallam wanted me to change it. I don't see a reason not to do Fee1 and Fee2 though.

**Comment by AdityaSripal** [comment]
It's simpler with just one fee

**Comment by hamdiallam** [comment]
I think we should have the option of fee1 and fee2 in case two different people want to create a transaction. The most common case will have fee2 zero'ed out but having the support in beneficial in my opinion

**Comment by hamdiallam** [comment]
Can we also include the specific required truffle and solc versions needed to build successfully in the readme

**Comment by colin-axner** [comment]
I added the spec for truffle solc versions to the contributions page. Seemed redundant to have that in two places. I can add it to both though if that is better

**Pull request merged**
